routes/web.php
<?php


Route::get('/', function () { return redirect('dashboard'); });

Route::get('blank', function () {
    return view('blank');
});

Auth::routes();


Route::group(
    [
        'prefix' => LaravelLocalization::setLocale(),
        'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath', 'auth' ]
    ],
    function()
    {
        Route::get('dashboard', 'DashboardController@index')->name('dashboard');

        // Administrator Setting
        Route::get('role-permission', 'RoleController@index')->name('role-permission');
        Route::post('save-permission', 'RoleController@savePermission')->name('savePermission');
        Route::resource('permission', 'PermissionController');
        Route::resource('countries', 'CountryController');
        Route::resource('operators', 'OperatorController');
        Route::resource('sms-gateway', 'SmsgatewayController');
        Route::resource('payment-method', 'PaymentMethodController');

        // Helper Controller
        Route::post('status-change', 'HelperController@statusChange')->name('status-change');
        Route::post('switch-user', 'HelperController@switchUser')->name('switch-user');


        // Users
        Route::resource('admin', 'AdminController');
        Route::resource('master-reseller', 'MasterResellerController');
        Route::resource('reseller', 'ResellerController');
        Route::resource('user', 'UsersController');
        Route::get('customer/create', 'CustomerController@create')->name('customer.create');
        Route::post('customer', 'CustomerController@store')->name('customer.store');
        Route::get('profile/{name}', 'ProfileController@index')->name('profile');
        Route::put('profile/{id}', 'ProfileController@update')->name('profile.update');
        Route::put('profile/password-change/{id}', 'ProfileController@passwordChange')->name('profile.password.change');

        // Default Pricing
        Route::resource('default-pricing', 'DefaultPricingController');
        Route::resource('pricing-coverages', 'PricingCoveragesController');

        // Transaction
        Route::resource('transaction', 'TransactionController');
        Route::resource('balance', 'BalanceController');

        // Api Settings
        Route::get('api', 'ApiController@index')->name('api.settings');
        Route::post('api', 'ApiController@generate')->name('api.generate');

        // PhoneBook
        Route::resource('group', 'GroupController');
        Route::resource('contacts', 'PhoneController');
        Route::resource('blocked-contacts', 'BlockedContactController');
        Route::post('file-input-contact', 'FileInputContact@store')->name('file.input.contact');

        // Send Message
        Route::get('send-sms', 'SendMessageController@index')->name('send-sms.index');
        Route::get('send-group-sms', 'SendMessageController@group')->name('send-sms.group');
        Route::get('send-file-sms', 'SendMessageController@file')->name('send-sms.file');
        Route::post('send-sms', 'SendMessageController@store')->name('send-sms.store');
        Route::resource('preview-sms', 'PreviewSmsController');
        Route::resource('sms', 'SmsController');
        Route::get('custom-sms', 'CustomSmsController@index')->name('custom-sms.index');
        Route::get('custom-sms/show/{id}', 'CustomSmsController@show')->name('custom-sms.show');
        Route::get('custom-sms/draft', 'CustomSmsController@draft')->name('custom-sms.draft');
        Route::post('custom-sms', 'CustomSmsController@store')->name('custom-sms.store');
        Route::post('custom-sms/sendSMS', 'CustomSmsController@sendSMS')->name('custom-sms.sendSMS');
        Route::DELETE('custom-sms/destroy/{id}', 'CustomSmsController@destroy')->name('custom-sms.destroy');

        // Masking
        Route::resource('masking', 'MaskingController');
        Route::get('add-masking/{name}', 'AddMasking@index')->name('add-masking');
        Route::post('add-masking', 'AddMasking@store')->name('add-masking.store');

        // All Report
        Route::prefix('report')->group(function () {
            Route::get('all-sms', 'ReportController@allSms')->name('report.allSms');
            Route::get('all-sms/view/{id}', 'ReportController@allSmsView')->name('allSmsView');
            Route::get('all-sms/download/{id}', 'ReportController@download');
            Route::get('routing-wise-total-sms', 'ReportController@routingSmsTotal')->name('report.routingSmsTotal');
            Route::get('routing-wise-sms', 'ReportController@routingSms')->name('report.routingSms');
            Route::get('user-usage', 'ReportController@userUsage')->name('report.userUsage');
            Route::get('user-usage-details', 'ReportController@userUsageDetails')->name('report.userUsageDetails');
            Route::get('user-balance', 'ReportController@userBalance')->name('report.userBalance');
            Route::get('transaction', 'ReportController@transaction')->name('report.transaction');
        });

        Route::resource('template', 'TemplateController');



    });

resources/views/admin/index.blade.php
@extends('layouts.app')

@section('title', 'All Admin')

@section('breadcrumb')
    <li class="active">All Admin</li>
@endsection

@push('header-scripts')
    <link href={{asset("assets/css/lib/data-table/buttons.bootstrap.min.css")}} rel="stylesheet" />
@endpush

@push('footer-scripts')
    <script src={{asset("assets/js/lib/data-table/datatables.min.js")}}></script>
    <script src={{asset("assets/js/lib/data-table/dataTables.buttons.min.js")}}></script>
    <script src={{asset("assets/js/lib/data-table/buttons.flash.min.js")}}></script>
    <script src={{asset("assets/js/lib/data-table/jszip.min.js")}}></script>
    <script src={{asset("assets/js/lib/data-table/pdfmake.min.js")}}></script>
    <script src={{asset("assets/js/lib/data-table/vfs_fonts.js")}}></script>
    <script src={{asset("assets/js/lib/data-table/buttons.html5.min.js")}}></script>
    <script src={{asset("assets/js/lib/data-table/buttons.print.min.js")}}></script>
    <script src={{asset("assets/js/lib/data-table/datatables-init.js")}}></script>
@endpush


@section('content')
    <div class="row">
        <div class="col-lg-12">
            <div class="card alert">
                <div class="card-header">
                    <h4>All Admin </h4>
                </div>
                <hr>
                <div class="bootstrap-data-table-panel">
                    <div class="table-responsive">
                        <table id="bootstrap-data-table-export" class="table table-striped table-bordered">
                            <thead>
                            <tr>
                                <th>Full Name</th>
                                <th>User Name</th>
                                <th>Email</th>
                                <th>Phone</th>
                                <th>Pricing Type</th>
                                @if(in_array(38, $user_permissions))
                                <th>Balance</th>
                                @endif
                                @if(in_array(39, $user_permissions))
                                <th>Status</th>
                                @endif
                                <th style="width:120px;">Option</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($admins as $value)
                                <tr>
                                    <td>{{ $value->first_name }} {{ $value->last_name }}</td>
                                    <td>{{ $value->username }}</td>
                                    <td>{{ $value->email }}</td>
                                    <td>{{ $value->phone }}</td>
                                    <td>{{ $value->price_type ? "SMS Pricing" : "Money Pricing" }}</td>
                                    @if(in_array(38, $user_permissions))
                                    <td><a class='btn btn-default btn-xs' href='{{ route('transaction.index') }}?name={{ $value->username }}'>BDT: {{ \App\Classes\Helper::transactionBalance($value->id) }}</a></td>
                                    @endif
                                    @if(in_array(39, $user_permissions))
                                    <td>
                                        <form id="status-change-{{ $value->id }}" method="post" action="{{ route('status-change', $value->id) }}" style="display: none;">
                                        @csrf
                                        <input type="hidden" name="table" value="users">
                                        <input type="hidden" name="id" value="{{ $value->id }}">
                                        <input type="hidden" name="column" value="status">
                                        <input type="hidden" name="value" value="{{ $value->status }}">
                                        <input type="hidden" name="message" value="User Status Change">
                                        </form>
                                        <a class='{{ $value->status ? 'btn btn-info btn-xs' : 'btn btn-warning btn-xs' }}' href="" onclick="
                                           if(confirm('Are you sure, You Want to Change this?'))
                                          {
                                            event.preventDefault();
                                            document.getElementById('status-change-{{ $value->id }}').submit();
                                          }
                                          else{
                                            event.preventDefault();
                                          }" >{{ $value->status ? 'Active' : 'Pending' }}</a>
                                    </td>
                                    @endif
                                    <td>
                                        @if(in_array(40, $user_permissions))
                                        <a href="{{ route('admin.show', $value->username) }}"><i class="ti-user color-dark"></i></a>
                                        @endif
                                        @if(in_array(41, $user_permissions))
                                        <a href="{{ route('admin.edit', $value->id) }}"><i class="ti-pencil-alt color-success"></i></a>
                                        @endif
                                        @if(in_array(42, $user_permissions))
                                        <form id="delete-form-{{ $value->id }}" method="post" action="{{ route('admin.destroy', $value->id) }}" style="display: none">
                                        @csrf
                                        @method('Delete')
                                        </form>
                                        <a href="" onclick="
                                          if(confirm('Are you sure, You Want to delete this?'))
                                          {
                                            event.preventDefault();
                                            document.getElementById('delete-form-{{ $value->id }}').submit();
                                          }
                                          else{
                                            event.preventDefault();
                                          }" ><i class="ti-trash color-danger"></i>
                                        </a>
                                        @endif
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <!-- /# card -->
        </div>
        <!-- /# column -->
    </div>
@endsection