routes/web.php
<?php


Route::get('/', function () { return redirect('dashboard'); });

Route::get('blank', function () {
    return view('blank');
});

Auth::routes();


Route::group(
    [
        'prefix' => LaravelLocalization::setLocale(),
        'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath', 'auth' ]
    ],
    function()
    {
        Route::get('dashboard', 'DashboardController@index')->name('dashboard');

        // Administrator Setting
        Route::get('role-permission', 'RoleController@index')->name('role-permission');
        Route::post('save-permission', 'RoleController@savePermission')->name('savePermission');
        Route::resource('permission', 'PermissionController');
        Route::resource('countries', 'CountryController');
        Route::resource('operators', 'OperatorController');
        Route::resource('sms-gateway', 'SmsgatewayController');
        Route::resource('payment-method', 'PaymentMethodController');

        // Helper Controller
        Route::post('status-change', 'HelperController@statusChange')->name('status-change');
        Route::post('switch-user', 'HelperController@switchUser')->name('switch-user');


        // Users
        Route::resource('admin', 'AdminController');
        Route::resource('master-reseller', 'MasterResellerController');
        Route::resource('reseller', 'ResellerController');
        Route::resource('user', 'UsersController');
        Route::get('customer/create', 'CustomerController@create')->name('customer.create');
        Route::post('customer', 'CustomerController@store')->name('customer.store');
        Route::get('profile/{name}', 'ProfileController@index')->name('profile');
        Route::put('profile/{id}', 'ProfileController@update')->name('profile.update');
        Route::put('profile/password-change/{id}', 'ProfileController@passwordChange')->name('profile.password.change');

        // Default Pricing
        Route::resource('default-pricing', 'DefaultPricingController');
        Route::resource('pricing-coverages', 'PricingCoveragesController');

        // Transaction
        Route::resource('transaction', 'TransactionController');
        Route::resource('balance', 'BalanceController');

        // Api Settings
        Route::get('api', 'ApiController@index')->name('api.settings');
        Route::post('api', 'ApiController@generate')->name('api.generate');

        // PhoneBook
        Route::resource('group', 'GroupController');
        Route::resource('contacts', 'PhoneController');
        Route::resource('blocked-contacts', 'BlockedContactController');
        Route::post('file-input-contact', 'FileInputContact@store')->name('file.input.contact');

        // Send Message
        Route::get('send-sms', 'SendMessageController@index')->name('send-sms.index');
        Route::get('send-group-sms', 'SendMessageController@group')->name('send-sms.group');
        Route::get('send-file-sms', 'SendMessageController@file')->name('send-sms.file');
        Route::post('send-sms', 'SendMessageController@store')->name('send-sms.store');
        Route::resource('preview-sms', 'PreviewSmsController');
        Route::resource('sms', 'SmsController');
        Route::get('custom-sms', 'CustomSmsController@index')->name('custom-sms.index');
        Route::get('custom-sms/show/{id}', 'CustomSmsController@show')->name('custom-sms.show');
        Route::get('custom-sms/draft', 'CustomSmsController@draft')->name('custom-sms.draft');
        Route::post('custom-sms', 'CustomSmsController@store')->name('custom-sms.store');
        Route::post('custom-sms/sendSMS', 'CustomSmsController@sendSMS')->name('custom-sms.sendSMS');
        Route::DELETE('custom-sms/destroy/{id}', 'CustomSmsController@destroy')->name('custom-sms.destroy');

        // Masking
        Route::resource('masking', 'MaskingController');
        Route::get('add-masking/{name}', 'AddMasking@index')->name('add-masking');
        Route::post('add-masking', 'AddMasking@store')->name('add-masking.store');

        // All Report
        Route::prefix('report')->group(function () {
            Route::get('all-sms', 'ReportController@allSms')->name('report.allSms');
            Route::get('all-sms/view/{id}', 'ReportController@allSmsView')->name('allSmsView');
            Route::get('all-sms/download/{id}', 'ReportController@download');
            Route::get('routing-wise-total-sms', 'ReportController@routingSmsTotal')->name('report.routingSmsTotal');
            Route::get('routing-wise-sms', 'ReportController@routingSms')->name('report.routingSms');
            Route::get('user-usage', 'ReportController@userUsage')->name('report.userUsage');
            Route::get('user-usage-details', 'ReportController@userUsageDetails')->name('report.userUsageDetails');
            Route::get('user-balance', 'ReportController@userBalance')->name('report.userBalance');
            Route::get('transaction', 'ReportController@transaction')->name('report.transaction');
        });

        Route::resource('template', 'TemplateController');



    });

resources/views/template/_form.blade.php
<div class="basic-form m-t-20">
    <div class="form-group">
        <label>Name</label>
        <input type="text" class="form-control border-none input-flat bg-ash" name="name" placeholder="Template Name" value="{{ old('name',$template->name) }}">
    </div>
</div>

<div class="basic-form m-t-20">
    <div class="form-group">
        <label>Content</label>
        <textarea class="form-control border-none input-flat bg-ash" name="content" cols="30" rows="10">{{ old('content',$template->content) }}</textarea>
    </div>
</div>

resources/views/template/index.blade.php
@extends('layouts.app')

@section('title', 'Template')

@section('breadcrumb')
    <li class="active">Template</li>
@endsection

@push('header-scripts')
    <link href={{asset("assets/css/lib/data-table/buttons.bootstrap.min.css")}} rel="stylesheet" />
@endpush

@push('footer-scripts')
    <script src={{asset("assets/js/lib/data-table/datatables.min.js")}}></script>
    <script src={{asset("assets/js/lib/data-table/dataTables.buttons.min.js")}}></script>
    <script src={{asset("assets/js/lib/data-table/buttons.flash.min.js")}}></script>
    <script src={{asset("assets/js/lib/data-table/jszip.min.js")}}></script>
    <script src={{asset("assets/js/lib/data-table/pdfmake.min.js")}}></script>
    <script src={{asset("assets/js/lib/data-table/vfs_fonts.js")}}></script>
    <script src={{asset("assets/js/lib/data-table/buttons.html5.min.js")}}></script>
    <script src={{asset("assets/js/lib/data-table/buttons.print.min.js")}}></script>
    <script src={{asset("assets/js/lib/data-table/datatables-init.js")}}></script>
@endpush


@section('content')
    <div class="row">
        <div class="col-md-3">
            <div class="card alert">
                <div class="card-header pr">
                    @if($template->exists)
                        <h4>Edit Template</h4>
                    @else
                        <h4>Add New Template</h4>
                    @endif
                </div>

                @if($template->exists)
                    <form method="POST" action="{{ route('template.update', $template->id) }}">
                        @method('PATCH')
                        @else
                            <form action="{{ route('template.store') }}" method="POST">
                                @endif
                                @csrf

                                @include('template._form')

                                @if($template->exists)
                                    <button class="btn btn-default btn-lg m-b-10 border-none m-r-5 sbmt-btn" type="submit">Edit Enter</button>
                                    <a class="btn btn-info btn-lg m-b-10 border-none m-r-5 sbmt-btn" href="{{ route('template.index') }}">Back</a>
                                @else
                                    <button class="btn btn-default btn-lg m-b-10 border-none m-r-5 sbmt-btn" type="submit">Submit Enter</button>
                                @endif
                            </form>
            </div>
        </div>
        <div class="col-lg-9">
            <div class="card alert">
                <div class="card-header">
                    <h4>All Template </h4>
                </div>
                <hr>
                @include('common.datatable')
            </div>
            <!-- /# card -->
        </div>
        <!-- /# column -->
    </div>
@endsection