routes/web.php
<?php


Route::get('/', function () { return redirect('dashboard'); });

Route::get('blank', function () {
    return view('blank');
});

Auth::routes();


Route::group(
    [
        'prefix' => LaravelLocalization::setLocale(),
        'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath', 'auth' ]
    ],
    function()
    {
        Route::get('dashboard', 'DashboardController@index')->name('dashboard');

        // Administrator Setting
        Route::get('role-permission', 'RoleController@index')->name('role-permission');
        Route::post('save-permission', 'RoleController@savePermission')->name('savePermission');
        Route::resource('permission', 'PermissionController');
        Route::resource('countries', 'CountryController');
        Route::resource('operators', 'OperatorController');
        Route::resource('sms-gateway', 'SmsgatewayController');
        Route::resource('payment-method', 'PaymentMethodController');

        // Helper Controller
        Route::post('status-change', 'HelperController@statusChange')->name('status-change');
        Route::post('switch-user', 'HelperController@switchUser')->name('switch-user');


        // Users
        Route::resource('admin', 'AdminController');
        Route::resource('master-reseller', 'MasterResellerController');
        Route::resource('reseller', 'ResellerController');
        Route::resource('user', 'UsersController');
        Route::get('customer/create', 'CustomerController@create')->name('customer.create');
        Route::post('customer', 'CustomerController@store')->name('customer.store');
        Route::get('profile/{name}', 'ProfileController@index')->name('profile');
        Route::put('profile/{id}', 'ProfileController@update')->name('profile.update');
        Route::put('profile/password-change/{id}', 'ProfileController@passwordChange')->name('profile.password.change');

        // Default Pricing
        Route::resource('default-pricing', 'DefaultPricingController');
        Route::resource('pricing-coverages', 'PricingCoveragesController');

        // Transaction
        Route::resource('transaction', 'TransactionController');
        Route::resource('balance', 'BalanceController');

        // Api Settings
        Route::get('api', 'ApiController@index')->name('api.settings');
        Route::post('api', 'ApiController@generate')->name('api.generate');

        // PhoneBook
        Route::resource('group', 'GroupController');
        Route::resource('contacts', 'PhoneController');
        Route::resource('blocked-contacts', 'BlockedContactController');
        Route::post('file-input-contact', 'FileInputContact@store')->name('file.input.contact');

        // Send Message
        Route::get('send-sms', 'SendMessageController@index')->name('send-sms.index');
        Route::get('send-group-sms', 'SendMessageController@group')->name('send-sms.group');
        Route::get('send-file-sms', 'SendMessageController@file')->name('send-sms.file');
        Route::post('send-sms', 'SendMessageController@store')->name('send-sms.store');
        Route::resource('preview-sms', 'PreviewSmsController');
        Route::resource('sms', 'SmsController');
        Route::get('custom-sms', 'CustomSmsController@index')->name('custom-sms.index');
        Route::get('custom-sms/show/{id}', 'CustomSmsController@show')->name('custom-sms.show');
        Route::get('custom-sms/draft', 'CustomSmsController@draft')->name('custom-sms.draft');
        Route::post('custom-sms', 'CustomSmsController@store')->name('custom-sms.store');
        Route::post('custom-sms/sendSMS', 'CustomSmsController@sendSMS')->name('custom-sms.sendSMS');
        Route::DELETE('custom-sms/destroy/{id}', 'CustomSmsController@destroy')->name('custom-sms.destroy');

        // Masking
        Route::resource('masking', 'MaskingController');
        Route::get('add-masking/{name}', 'AddMasking@index')->name('add-masking');
        Route::post('add-masking', 'AddMasking@store')->name('add-masking.store');

        // All Report
        Route::prefix('report')->group(function () {
            Route::get('all-sms', 'ReportController@allSms')->name('report.allSms');
            Route::get('all-sms/view/{id}', 'ReportController@allSmsView')->name('allSmsView');
            Route::get('all-sms/download/{id}', 'ReportController@download');
            Route::get('routing-wise-total-sms', 'ReportController@routingSmsTotal')->name('report.routingSmsTotal');
            Route::get('routing-wise-sms', 'ReportController@routingSms')->name('report.routingSms');
            Route::get('user-usage', 'ReportController@userUsage')->name('report.userUsage');
            Route::get('user-usage-details', 'ReportController@userUsageDetails')->name('report.userUsageDetails');
            Route::get('user-balance', 'ReportController@userBalance')->name('report.userBalance');
            Route::get('transaction', 'ReportController@transaction')->name('report.transaction');
        });

        Route::resource('template', 'TemplateController');



    });

app/Http/Controllers/TransactionController.php
<?php

namespace App\Http\Controllers;

use App\Classes\Helper;
use App\Http\Requests\TransactionRequest;
use App\Log;
use App\PaymentMethod;
use App\Transaction;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Session;

class TransactionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $user = User::where('username', $request->name)->first();
        $transactions = Transaction::where('user_id', $user->id)->get();
        $transaction = new Transaction;
        $paymentMethod = PaymentMethod::where('status', 1)->get();

        $col_data=array();
        $col_heads = array(
            trans('messages.State'),
            trans('messages.Payment Method'),
            trans('messages.Description'),
            trans('messages.Amount'),
            trans('messages.Created At'),
            trans('messages.Option')
        );

        foreach ($transactions as $value) {
            $form_url = route('transaction.destroy', $value->id);
            $edit_url = route('transaction.edit', $value->id);
            $col_data[] = array(
                $value->state ? "Credit" : "Debit",
                $value->payment_method,
                $value->description,
                $value->state ? "<span class=\"label label-primary\">$value->amount</span>" : "<span class=\"label label-danger\">$value->amount</span>",
                $value->created_at,
                "<a href=\"$edit_url\"><i class=\"ti-pencil-alt color-success\"></i></a> " .
                Helper::delete_form($form_url, $value->id)
            );
        }

        return view('transaction.index', compact('transaction', 'col_heads', 'col_data', 'user', 'paymentMethod'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(TransactionRequest $request)
    {
        $data = $request->all();
        Transaction::create($data);

        $message = "Add Transaction";
        Session::flash('success', $message);
        Log::create(['user_id' => Auth::id(), 'description' => $message]);
        return back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $transaction = Transaction::find($id);
        $transactions = Transaction::where('user_id', $transaction->user_id)->get();
        $user = User::where('id', $transaction->user_id)->first();
        $paymentMethod = PaymentMethod::where('status', 1)->get();

        $col_data=array();
        $col_heads = array(
            trans('messages.State'),
            trans('messages.Payment Method'),
            trans('messages.Description'),
            trans('messages.Amount'),
            trans('messages.Created At'),
            trans('messages.Option')
        );

        foreach ($transactions as $value) {
            $form_url = route('transaction.destroy', $value->id);
            $edit_url = route('transaction.edit', $value->id);
            $col_data[] = array(
                $value->state ? "Credit" : "Debit",
                $value->payment_method,
                $value->description,
                $value->state ? "<span class=\"label label-primary\">$value->amount</span>" : "<span class=\"label label-danger\">$value->amount</span>",
                $value->created_at,
                "<a href=\"$edit_url\"><i class=\"ti-pencil-alt color-success\"></i></a> " .
                Helper::delete_form($form_url, $value->id)
            );
        }

        return view('transaction.index', compact('transaction', 'col_heads', 'col_data', 'user', 'paymentMethod'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = $request->all();
        $transaction = Transaction::find($id);
        $transaction->fill($data);
        $transaction->save();

        $message = "Edit Transaction";
        Session::flash('success', $message);
        Log::create(['user_id' => Auth::id(), 'description' => $message]);
        return back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $transaction = Transaction::find($id);
        $transaction->delete();

        $message = "Delete Transaction";
        Session::flash('success', $message);
        Log::create(['user_id' => Auth::id(), 'description' => $message]);
        return back();
    }
}

resources/views/transaction/_form.blade.php
<div class="basic-form m-t-20">
    <div class="form-group">
        <label>Payment Method</label>
        <select class="form-control bg-ash border-none js-example-basic-single" name="payment_method">
            <option></option>
            @if($transaction->exists)
                @foreach($paymentMethod as $value)
                    <option value="{{ $value->name }}" @if($value->name == $transaction->payment_method) selected @endif>{{ $value->name }}</option>
                @endforeach
            @else
                @foreach($paymentMethod as $value)
                    <option value="{{ $value->name }}">{{ $value->name }}</option>
                @endforeach
            @endif
        </select>
    </div>
</div>

<div class="basic-form m-t-20">
    <div class="form-group">
        <label>Description</label>
        <textarea class="form-control border-none input-flat bg-ash" rows="3" name="description" placeholder="Description" >{{ old('description',$transaction->description) }}</textarea>
    </div>
</div>

<div class="basic-form m-t-20">
    <div class="form-group">
        <label>Amount</label>
        <input type="number" class="form-control border-none input-flat bg-ash" name="amount" placeholder="Amount" value="{{ old('amount',$transaction->amount) }}">
    </div>
</div>

<div class="basic-form m-t-20">
    <div class="form-group">
        <label>Add or Deduct Balance</label>
        @if($transaction->exists)
            <div class="row">
                <div class="col-md-6">
                    <div class="basic-form">
                        <div class="form-group">
                            <div class="form-check">
                                <input type="radio" name="state" value="0" @if($transaction->state ==0) checked @endif >
                                <label class="form-check-label" for="type">
                                    Deduct
                                </label>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="basic-form">
                        <div class="form-group">
                            <div class="form-check">
                                <input type="radio" name="state" value="1" @if($transaction->state ==1) checked @endif>
                                <label class="form-check-label" for="type">
                                    Add
                                </label>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        @else
            <div class="row">
                <div class="col-md-6">
                    <div class="basic-form">
                        <div class="form-group">
                            <div class="form-check">
                                <input type="radio" name="state" value="0">
                                <label class="form-check-label" for="type">
                                    Deduct
                                </label>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="basic-form">
                        <div class="form-group">
                            <div class="form-check">
                                <input type="radio" name="state" value="1" checked>
                                <label class="form-check-label" for="type">
                                    Add
                                </label>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        @endif
    </div>
</div>

resources/views/transaction/index.blade.php
@extends('layouts.app')

@section('title', 'Transaction')

@section('breadcrumb')
    <li class="active">Transaction</li>
@endsection

@push('header-scripts')
    <link href={{asset("assets/css/lib/data-table/buttons.bootstrap.min.css")}} rel="stylesheet" />
    <link href={{ asset("css/select2.min.css") }} rel="stylesheet" />
@endpush

@push('footer-scripts')
    <script src={{asset("assets/js/lib/data-table/datatables.min.js")}}></script>
    <script src={{asset("assets/js/lib/data-table/dataTables.buttons.min.js")}}></script>
    <script src={{asset("assets/js/lib/data-table/buttons.flash.min.js")}}></script>
    <script src={{asset("assets/js/lib/data-table/jszip.min.js")}}></script>
    <script src={{asset("assets/js/lib/data-table/pdfmake.min.js")}}></script>
    <script src={{asset("assets/js/lib/data-table/vfs_fonts.js")}}></script>
    <script src={{asset("assets/js/lib/data-table/buttons.html5.min.js")}}></script>
    <script src={{asset("assets/js/lib/data-table/buttons.print.min.js")}}></script>
    <script src={{asset("assets/js/lib/data-table/datatables-init.js")}}></script>
    <script src={{ asset("js/select2.min.js") }}></script>
    <script>
        $(document).ready(function() {
            $('.js-example-basic-single').select2({
                allowClear: true,
                placeholder: 'Select an option'
            });
        });
    </script>
@endpush


@section('content')
    <div class="row">
        <div class="col-md-3">
            <div class="card alert">
                <div class="card-header pr">
                    @if($transaction->exists)
                        <h4>Edit Transaction</h4>
                    @else
                        <h4>Add New Transaction</h4>
                    @endif
                </div>

                @if($transaction->exists)
                    <form method="POST" action="{{ route('transaction.update', $transaction->id) }}">
                        @method('PATCH')
                        @else
                            <form action="{{ route('transaction.store') }}" method="POST">
                                @endif
                                @csrf
                                <input type="hidden" name="user_id" value="{{ $user->id }}">

                                @include('transaction._form')

                                @if($transaction->exists)
                                    <button class="btn btn-default btn-lg m-b-10 border-none m-r-5 sbmt-btn" type="submit">Edit Enter</button>
                                    <a class="btn btn-info btn-lg m-b-10 border-none m-r-5 sbmt-btn" href="{{ route('transaction.index') }}?name={{$user->username}}">Back</a>
                                @else
                                    <button class="btn btn-default btn-lg m-b-10 border-none m-r-5 sbmt-btn" type="submit">Submit Enter</button>
                                @endif
                            </form>
            </div>
        </div>
        <div class="col-lg-9">
            <div class="card alert">
                <div class="card-header">
                    <h4>All Transaction </h4>
                    <span class="pull-right label label-default">TK: {{ \App\Classes\Helper::transactionBalance($user->id) }}</span>
                </div>
                <hr>
                @include('common.datatable')
            </div>
            <!-- /# card -->
        </div>
        <!-- /# column -->
    </div>
@endsection