routes/web.php
<?php


Route::get('/', function () { return redirect('dashboard'); });

Route::get('blank', function () {
    return view('blank');
});

Auth::routes();


Route::group(
    [
        'prefix' => LaravelLocalization::setLocale(),
        'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath', 'auth' ]
    ],
    function()
    {
        Route::get('dashboard', 'DashboardController@index')->name('dashboard');

        // Administrator Setting
        Route::get('role-permission', 'RoleController@index')->name('role-permission');
        Route::post('save-permission', 'RoleController@savePermission')->name('savePermission');
        Route::resource('permission', 'PermissionController');
        Route::resource('countries', 'CountryController');
        Route::resource('operators', 'OperatorController');
        Route::resource('sms-gateway', 'SmsgatewayController');
        Route::resource('payment-method', 'PaymentMethodController');

        // Helper Controller
        Route::post('status-change', 'HelperController@statusChange')->name('status-change');
        Route::post('switch-user', 'HelperController@switchUser')->name('switch-user');


        // Users
        Route::resource('admin', 'AdminController');
        Route::resource('master-reseller', 'MasterResellerController');
        Route::resource('reseller', 'ResellerController');
        Route::resource('user', 'UsersController');
        Route::get('customer/create', 'CustomerController@create')->name('customer.create');
        Route::post('customer', 'CustomerController@store')->name('customer.store');
        Route::get('profile/{name}', 'ProfileController@index')->name('profile');
        Route::put('profile/{id}', 'ProfileController@update')->name('profile.update');
        Route::put('profile/password-change/{id}', 'ProfileController@passwordChange')->name('profile.password.change');

        // Default Pricing
        Route::resource('default-pricing', 'DefaultPricingController');
        Route::resource('pricing-coverages', 'PricingCoveragesController');

        // Transaction
        Route::resource('transaction', 'TransactionController');
        Route::resource('balance', 'BalanceController');

        // Api Settings
        Route::get('api', 'ApiController@index')->name('api.settings');
        Route::post('api', 'ApiController@generate')->name('api.generate');

        // PhoneBook
        Route::resource('group', 'GroupController');
        Route::resource('contacts', 'PhoneController');
        Route::resource('blocked-contacts', 'BlockedContactController');
        Route::post('file-input-contact', 'FileInputContact@store')->name('file.input.contact');

        // Send Message
        Route::get('send-sms', 'SendMessageController@index')->name('send-sms.index');
        Route::get('send-group-sms', 'SendMessageController@group')->name('send-sms.group');
        Route::get('send-file-sms', 'SendMessageController@file')->name('send-sms.file');
        Route::post('send-sms', 'SendMessageController@store')->name('send-sms.store');
        Route::resource('preview-sms', 'PreviewSmsController');
        Route::resource('sms', 'SmsController');
        Route::get('custom-sms', 'CustomSmsController@index')->name('custom-sms.index');
        Route::get('custom-sms/show/{id}', 'CustomSmsController@show')->name('custom-sms.show');
        Route::get('custom-sms/draft', 'CustomSmsController@draft')->name('custom-sms.draft');
        Route::post('custom-sms', 'CustomSmsController@store')->name('custom-sms.store');
        Route::post('custom-sms/sendSMS', 'CustomSmsController@sendSMS')->name('custom-sms.sendSMS');
        Route::DELETE('custom-sms/destroy/{id}', 'CustomSmsController@destroy')->name('custom-sms.destroy');

        // Masking
        Route::resource('masking', 'MaskingController');
        Route::get('add-masking/{name}', 'AddMasking@index')->name('add-masking');
        Route::post('add-masking', 'AddMasking@store')->name('add-masking.store');

        // All Report
        Route::prefix('report')->group(function () {
            Route::get('all-sms', 'ReportController@allSms')->name('report.allSms');
            Route::get('all-sms/view/{id}', 'ReportController@allSmsView')->name('allSmsView');
            Route::get('all-sms/download/{id}', 'ReportController@download');
            Route::get('routing-wise-total-sms', 'ReportController@routingSmsTotal')->name('report.routingSmsTotal');
            Route::get('routing-wise-sms', 'ReportController@routingSms')->name('report.routingSms');
            Route::get('user-usage', 'ReportController@userUsage')->name('report.userUsage');
            Route::get('user-usage-details', 'ReportController@userUsageDetails')->name('report.userUsageDetails');
            Route::get('user-balance', 'ReportController@userBalance')->name('report.userBalance');
            Route::get('transaction', 'ReportController@transaction')->name('report.transaction');
        });

        Route::resource('template', 'TemplateController');



    });

app/Masking.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Masking extends Model
{
    protected $fillable = ['user_id', 'display_name', 'name', 'status', 'approved_at'];

    public function users()
    {
        return $this->belongsToMany('App\User', 'masking_user', 'user_id', 'masking_id');
    }

    public function user()
    {
        return $this->belongsTo('App\User');
    }
}

app/Http/Controllers/MaskingController.php
<?php

namespace App\Http\Controllers;

use App\Classes\Helper;
use App\Http\Requests\MaskingRequest;
use App\Log;
use App\Masking;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Session;

class MaskingController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $maskings = Masking::where('user_id', Auth::id())->latest()->get();
        $masking = new Masking;
        $col_data=array();
        $col_heads = array(
            trans('messages.Added At'),
            trans('messages.Masking / Sender ID'),
            trans('messages.Approved At'),
            trans('messages.Status'),
            trans('messages.Option')
        );

        foreach ($maskings as $value) {
            $form_url = route('masking.destroy', $value->id);
            $edit_url = route('masking.edit', $value->id);
            $col_data[] = array(
                $value->created_at,
                $value->display_name,
                $value->approved_at,
                $value->status ? 'Active' : 'Pending',
                "<a href=\"$edit_url\"><i class=\"ti-pencil-alt color-success\"></i></a> " .
                Helper::delete_form($form_url, $value->id)
            );
        }

        return view('masking.index', compact('col_heads', 'col_data', 'masking'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(MaskingRequest $request)
    {
        $data = $request->all();
        $data['user_id'] = Auth::id();
        if (isset($request->name)) {
            $data['name'] = $request->name;
        } else {
            $data['name'] = $request->display_name;
        }
        if (isset($request->status)) {
            if ($request->status==1) {
                $data['status'] = 1;
                $data['approved_at'] = Carbon::now();
            }
        }

        Masking::create($data);

        $message = "Add New Masking";
        Session::flash('success', $message);
        Log::create(['user_id' => Auth::id(), 'description' => $message]);
        return back();
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Masking  $masking
     * @return \Illuminate\Http\Response
     */
    public function show(Masking $masking)
    {

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Masking  $masking
     * @return \Illuminate\Http\Response
     */
    public function edit(Masking $masking)
    {
        $maskings = Masking::where('user_id', Auth::id())->get();
        $col_data=array();
        $col_heads = array(
            trans('messages.Added At'),
            trans('messages.Masking / Sender ID'),
            trans('messages.Approved At'),
            trans('messages.Status'),
            trans('messages.Option')
        );

        foreach ($maskings as $value) {
            $form_url = route('masking.destroy', $value->id);
            $edit_url = route('masking.edit', $value->id);
            $col_data[] = array(
                $value->created_at,
                $value->display_name,
                $value->approved_at,
                $value->status ? 'Active' : 'Pending',
                "<a href=\"$edit_url\"><i class=\"ti-pencil-alt color-success\"></i></a> " .
                Helper::delete_form($form_url, $value->id)
            );
        }

        return view('masking.index', compact('col_heads', 'col_data', 'masking'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Masking  $masking
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Masking $masking)
    {
        $data = $request->all();
        if ($request->status==1) {
            $data['approved_at'] = Carbon::now();
        } else {
            $data['approved_at'] = null;
        }

        $masking->update($data);

        $message = "Edit Masking";
        Session::flash('success', $message);
        Log::create(['user_id' => Auth::id(), 'description' => $message]);
        return back();

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Masking  $masking
     * @return \Illuminate\Http\Response
     */
    public function destroy(Masking $masking)
    {
        $masking->delete();

        $message = "Delete Masking";
        Session::flash('success', $message);
        Log::create(['user_id' => Auth::id(), 'description' => $message]);
        return back();
    }
}

resources/views/masking/_form.blade.php
<div class="basic-form m-t-20">
    <div class="form-group">
        <label>Sender ID </label>
        <input type="text" class="form-control border-none input-flat bg-ash" name="display_name" placeholder="Sender ID" value="{{ old('display_name',$masking->display_name) }}">
    </div>
</div>

@if(\Illuminate\Support\Facades\Auth::user()->role == 1)
    <div class="basic-form m-t-20">
        <div class="form-group">
            <label>Name </label>
            <input type="text" class="form-control border-none input-flat bg-ash" name="name" placeholder="Name" value="{{ old('name',$masking->name) }}">
        </div>
    </div>

    @if($masking->exists)
        <div class="basic-form m-t-20">
            <div class="form-group">
                <label class="col-sm-2 control-label">Status</label>
                <div class="col-sm-10">
                    <div class="row" style="margin-bottom: 20px;">
                        <div class="col-lg-6">
                            <input type="radio" name="status" value="1" @if($masking->status == 1) checked @endif > Active
                        </div>
                        <div class="col-lg-6">
                            <input type="radio" name="status" value="0" @if($masking->status == 0) checked @endif> Pending
                        </div>
                    </div>
                </div>
            </div>
        </div>
    @else
        <div class="basic-form m-t-20">
            <div class="form-group">
                <label class="col-sm-2 control-label">Status</label>
                <div class="col-sm-10">
                    <div class="row" style="margin-bottom: 20px;">
                        <div class="col-lg-6">
                            <input type="radio" name="status" value="1" checked> Active
                        </div>
                        <div class="col-lg-6">
                            <input type="radio" name="status" value="0"> Pending
                        </div>
                    </div>
                </div>
            </div>
        </div>
    @endif

@endif

resources/views/masking/add.blade.php
@extends('layouts.app')

@section('title', 'Masking Add')

@section('breadcrumb')
    <li class="active">Masking Add</li>
@endsection

@push('header-scripts')

@endpush

@push('footer-scripts')

@endpush


@section('content')
<div class="row">
    <div class="col-lg-12">
        <div class="card alert">
            <div class="card-header">
                <h4>Add Masking </h4>
                    @if($user->role == 1)
                        <a class="btn btn-default btn-lg m-b-10 border-none m-r-5 sbmt-btn btn-sm" style="float: right;" href="{{ route('admin.show', $user->username) }}">Back</a>
                    @elseif($user->role == 2)
                        <a class="btn btn-default btn-lg m-b-10 border-none m-r-5 sbmt-btn btn-sm" style="float: right;" href="{{ route('master-reseller.show', $user->username) }}">Back</a>
                    @elseif($user->role == 3)
                        <a class="btn btn-default btn-lg m-b-10 border-none m-r-5 sbmt-btn btn-sm" style="float: right;" href="{{ route('reseller.show', $user->username) }}">Back</a>
                    @else
                        <a class="btn btn-default btn-lg m-b-10 border-none m-r-5 sbmt-btn btn-sm" style="float: right;" href="{{ route('user.show', $user->username) }}">Back</a>
                    @endif
            </div>
            <hr>
            <div class="card-body">
                <form action="{{ route('add-masking.store') }}" method="POST">
                    @csrf
                    <input type="hidden" value="{{ $user->id }}" name="user_id">
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                        <tr>
                            <th style="width: 50px;">#</th>
                            <th>Masking Name</th>
                            <th>Apply</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($maskings as $masking)
                        <tr>
                            <td>{{ $loop->index + 1 }}</td>
                            <td>{{ $masking->display_name }} <span><code>{{ $masking->name }}</code></span></td>
                            <td><input type="checkbox" value="{{ $masking->id }}" name="masking_id[]" {!! (in_array($masking->id,$approvedMasking)) ? 'checked' : '' !!}></td>
                        </tr>
                        @endforeach
                        </tbody>
                    </table>
                    <button type="submit" class="btn btn-default m-b-10" style="float: right; margin-top: 20px;">Apply</button>
                </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/masking/index.blade.php
@extends('layouts.app')

@section('title', 'All Masking')

@section('breadcrumb')
    <li class="active">All Masking</li>
@endsection

@push('header-scripts')
    <link href={{asset("assets/css/lib/data-table/buttons.bootstrap.min.css")}} rel="stylesheet" />
    <link href={{ asset("css/select2.min.css") }} rel="stylesheet" />
@endpush

@push('footer-scripts')
    <script src={{asset("assets/js/lib/data-table/datatables.min.js")}}></script>
    <script src={{asset("assets/js/lib/data-table/dataTables.buttons.min.js")}}></script>
    <script src={{asset("assets/js/lib/data-table/buttons.flash.min.js")}}></script>
    <script src={{asset("assets/js/lib/data-table/jszip.min.js")}}></script>
    <script src={{asset("assets/js/lib/data-table/pdfmake.min.js")}}></script>
    <script src={{asset("assets/js/lib/data-table/vfs_fonts.js")}}></script>
    <script src={{asset("assets/js/lib/data-table/buttons.html5.min.js")}}></script>
    <script src={{asset("assets/js/lib/data-table/buttons.print.min.js")}}></script>
    <script src={{asset("assets/js/lib/data-table/datatables-init.js")}}></script>
    <script src={{ asset("js/select2.min.js") }}></script>
    <script>
        $(document).ready(function() {
            $('.js-example-basic-single').select2({
                allowClear: true,
                placeholder: 'Select an option'
            });
        });
    </script>
@endpush


@section('content')
    <div class="row">
        <div class="col-md-3">
            <div class="card alert">
                <div class="card-header pr">
                    @if($masking->exists)
                        <h4>Edit Masking</h4>
                    @else
                        <h4>Add New Masking</h4>
                    @endif
                </div>

                @if($masking->exists)
                <form method="POST" action="{{ route('masking.update', $masking->id) }}">
                    @method('PATCH')
                    @csrf
                @else
                <form action="{{ route('masking.store') }}" method="POST">
                    @csrf
                @endif

                @include('masking._form')

                    @if($masking->exists)
                        <button class="btn btn-default btn-lg m-b-10 border-none m-r-5 sbmt-btn" type="submit">Edit Enter</button>
                        <a class="btn btn-info btn-lg m-b-10 border-none m-r-5 sbmt-btn" href="{{ route('masking.index') }}">Back</a>
                    @else
                        <button class="btn btn-default btn-lg m-b-10 border-none m-r-5 sbmt-btn" type="submit">Submit Enter</button>
                    @endif
                </form>
            </div>
            <div class="card alert">

                <div class="card-header">
                    <h4>Masking Information</h4>
                </div>
                <div class="card-body">
                    <ul class="list-group">
                        <li class="list-group-item">Sender name can have up to 11 characters. Acceptable characters are: a-z A-Z 0-9 -. [space]. </li>

                        <li class="list-group-item">Each added sender name will be verified by our customer service team.Verification usually takes couple minutes in working hours. </li>



                    </ul>
                </div>
            </div>
        </div>
        <div class="col-lg-9">
            <div class="card alert">
                <div class="card-header">
                    <h4>All Masking </h4>
                </div>
                <hr>
                @include('common.datatable')
            </div>
            <!-- /# card -->
        </div>
        <!-- /# column -->
    </div>
@endsection